---
name: Docker Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build . -t yorch/photo-renamer

      - name: Test Docker image
        run: |
          # Run the container in detached mode to test it starts properly
          docker run -d --name checker yorch/photo-renamer

          # Wait a moment for the container to start
          sleep 2

          # Check the logs
          echo "Container logs:"
          docker logs checker

          # Show container status
          echo "Container status:"
          docker ps -a

          # Clean up
          docker rm -f checker