name: Run Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        go-version: [1.19, 1.20, 1.21]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
        
    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ matrix.go-version }}-${{ hashFiles('src/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-${{ matrix.go-version }}-
          ${{ runner.os }}-go-
          
    - name: Install dependencies
      working-directory: ./src
      run: go mod download
      
    - name: Run tests with coverage
      working-directory: ./src
      run: go test -v -coverprofile=coverage.out ./...
      
    - name: Generate coverage report
      working-directory: ./src
      run: go tool cover -html=coverage.out -o coverage.html
      
    - name: Upload coverage to artifacts
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report-go${{ matrix.go-version }}
        path: src/coverage.html
        
    - name: Display coverage summary
      working-directory: ./src
      run: go tool cover -func=coverage.out